# Generated by Django 4.1.4 on 2023-01-18 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='faq',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='faq',
            name='topic',
            field=models.ManyToManyField(to='faq.faqtopic'),
        ),
    ]
