# Generated by Django 4.1.4 on 2023-01-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faqtopic_alter_faq_options_faq_date_posted_faq_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='topic',
            field=models.ManyToManyField(related_name='faqtopic', to='faq.faqtopic'),
        ),
    ]
