# Generated by Django 4.1.4 on 2023-01-16 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_post_image_alter_answer_date_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_reply',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
