# Generated by Django 4.1.4 on 2023-01-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0005_topic_answer_is_anonymous_answer_pin_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_posted']},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='answer_reply',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
