# Generated by Django 4.1.4 on 2023-01-17 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0007_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_reply',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='ask.answer'),
        ),
    ]
