# Generated by Django 4.1.4 on 2023-01-18 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask', '0009_alter_answer_options_alter_answer_reply_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='voter',
            field=models.ManyToManyField(blank=True, null=True, to='ask.postvoter'),
        ),
        migrations.AddField(
            model_name='answer_reply',
            name='voter',
            field=models.ManyToManyField(blank=True, null=True, to='ask.postvoter'),
        ),
        migrations.AddField(
            model_name='post',
            name='voter',
            field=models.ManyToManyField(blank=True, null=True, to='ask.postvoter'),
        ),
    ]
