# Generated by Django 4.1.4 on 2023-01-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0010_postvoter_answer_voter_answer_reply_voter_post_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(default=1, upload_to='topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='voter',
            field=models.ManyToManyField(blank=True, to='ask.postvoter'),
        ),
        migrations.AlterField(
            model_name='post',
            name='voter',
            field=models.ManyToManyField(blank=True, to='ask.postvoter'),
        ),
    ]
