# Generated by Django 4.1.4 on 2023-01-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0012_alter_answer_reply_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(related_name='posttopic', to='ask.topic'),
        ),
    ]
