# Generated by Django 4.1.5 on 2023-01-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0013_alter_post_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='post'),
        ),
    ]
