# Generated by Django 4.1.5 on 2023-01-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0014_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='answer_reply',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='post',
            name='voter',
        ),
        migrations.AddField(
            model_name='answer',
            name='voter_down',
            field=models.ManyToManyField(blank=True, related_name='anwewr_voter_down', to='ask.postvoter'),
        ),
        migrations.AddField(
            model_name='answer',
            name='voter_up',
            field=models.ManyToManyField(blank=True, related_name='anwewr_voter_up', to='ask.postvoter'),
        ),
        migrations.AddField(
            model_name='answer_reply',
            name='voter_down',
            field=models.ManyToManyField(blank=True, related_name='ranwewr_voter_down', to='ask.postvoter'),
        ),
        migrations.AddField(
            model_name='answer_reply',
            name='voter_up',
            field=models.ManyToManyField(blank=True, related_name='ranwewr_voter_up', to='ask.postvoter'),
        ),
        migrations.AddField(
            model_name='post',
            name='voter_down',
            field=models.ManyToManyField(blank=True, related_name='voter_down', to='ask.postvoter'),
        ),
        migrations.AddField(
            model_name='post',
            name='voter_up',
            field=models.ManyToManyField(blank=True, related_name='voter_up', to='ask.postvoter'),
        ),
    ]
