# Generated by Django 4.1.5 on 2023-01-25 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_user_max_otp_try_remove_user_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='+923175041207', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits only.', regex='^\\d{13}')]),
        ),
    ]
