# Generated by Django 4.1.4 on 2023-01-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='i_answer',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='i_question',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
